version: '3.1'
services:
  db:
    image: postgres:9.6-alpine
    restart: unless-stopped
    container_name: buoydev-db
    env_file:
     - ./docker.env
    ports:
     - "5432:5432"
    networks:
      - buoy_apps
  web:
    build: .
    image: buoydev-py
    container_name: buoydev-web
    restart: unless-stopped
    command: ./entrypoint.sh
    env_file:
     - ./docker.env
    volumes:
      - .:/app/
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - buoy_apps

networks:
  buoy_apps:
    external: true
